### ISSUE TITLE
array gets "rolled back" to string

### ISSUE THREAD

**Issue by arne21** [danielspaniel/ember-data-change-tracker#11]
It wasn't quite clear to me from the README whether rolling back an array property should work (give me the original array back) or not (leaving the change in the array), so I tried it out. The result was ... unexpected: a _string representation_ of the original array.

```
$E.get('arrayProp')
[]
$E.get('arrayProp').push('something')
1
$E.get('arrayProp')
["something"]
$E.changed()
Object {arrayProp: true}
$E.rollback()
undefined
$E.get('arrayProp')
"[]"
```

**Comment by danielspaniel** [comment]
that sounds kind of fun actually .. but let me see what your model looks like ( how is the attribute defined ) ?  is there custom transform? or is it attr()  ?  
 if you give me some context/detail I can write a test for it and see what happens

**Comment by arne21** [comment]
oh, sorry. yeah, just `attr()`. Or, probably, `attr({defaultValue: () => Ember.A()})` (I'm away from my work computer at the moment.)

**Comment by danielspaniel** [comment]
ok .. i will see what I can find

**Comment by danielspaniel** [comment]
now fixed. that was a good find. thanks for bringing it up. kind of a whopper of a flaw too. 

https://github.com/danielspaniel/ember-data-change-tracker/releases/tag/v0.5.2

**Comment by sethboyles** [comment]
this is happening for me (0.7.7) but only for empty arrays (no custom transform)

**Comment by danielspaniel** [comment]
can you fork and run the tests ?  change the ED version to whatever you are running? might have to do with ember-data version .. not sure .. you ( or me ) might have to add a failing test to prove this
