### ISSUE TITLE
hasDirtyRelations seems not work any more

### ISSUE THREAD

**Issue by nightire** [danielspaniel/ember-data-change-tracker#12]
This is my first time to use this addon, so I don't know what's the status previously, but seems `hasDirtyRelations` CP not working.

this is the test:

![image](https://cloud.githubusercontent.com/assets/1104018/24369494/c475c10c-1356-11e7-9a8c-e3ad78d5fbe0.png)

this are the definitions for both model:

```javascript
// car-model
export default DS.Model.extend({
  name: attr('string'),
  description: attr('string'),
  disabled: attr('boolean'),

  'car-type': belongsTo('car-type'),
})

// car-type
export default DS.Model.extend({
  name: attr('string'),
  description: attr('string'),

  'car-models': hasMany('car-model'),
})

and I turned of `enableIsDirty` if `config/environment.js`:

```javascript
// in config/environment.js

    changeTracker: {
      trackHasMany: true,
      auto: false,
      enableIsDirty: true,
    },
```

I'm using the latest release ember (v2.12.0) and ember-data (v2.12.1).

**Comment by nightire** [comment]
Sorry my bad, I forgot to call `model.startTrack()`, however, this should be more easy to see in the README...

**Comment by danielspaniel** [comment]
Try setting auto: true  and it will work 
or you can set auto: true just on the model ( car-model ) .. check the docks

**Comment by danielspaniel** [comment]
maybe your right .. but this addon is trying to do as little as possible by default. 
 if you think the README could be improved, please feel free to update it and submit a PR.  
 There is always room for doc improvements
