### ISSUE TITLE
isDirty is true after save()?

### ISSUE THREAD

**Issue by mvrkljan** [danielspaniel/ember-data-change-tracker#13]
Not sure if this is by design or not, but after updating a `belongsTo` relationship and calling `save()` on the model, the `isDirty` property is still set to `true` after successful request, unlike the default Ember behavior with `hasDirtyAttributes`.

Is there a method that needs to be called manually to use the new state as a "clean" state? I tried with `saveChanges()` on successful save, but to no effect.

**Comment by danielspaniel** [comment]
that is good question .. your using the isDirty computed property .. hmmm .. let me round up the tests and see if I can duplicate that ( and fix it )

**Comment by mvrkljan** [comment]
Updated the package, didn't notice any change. Here's my code:

```js
// organizationUser model
export default DS.Model.extend({
    changeTracker: { enableIsDirty: true },
    isAdministrative: DS.attr('boolean'),
    organization: DS.belongsTo('organization'),
    user: DS.belongsTo('user')
});
```

```js
// action that changes organization relationship on some organizationUser models
setOrganization(organization) {
    this.get('user.organizationUsers').forEach(function(organizationUser) {
        organizationUser.startTrack();
        organizationUser.set('organization', organization);
    });
}
```

```js
// line in task that saves all dirty organizationUser models
yield user.get('organizationUsers').filterBy('isDirty').invoke('save');
```

The config you see in model is the only config present, so not using auto save and manually calling `startTrack()` before changing relationship.

`isDirty` behaves as expected before and after `setOrganization` executes, and only dirty models do get saved. But after invoking `save()` on all models models are still left with `isDirty` and `hasDirtyRelationships` set to `true` (observed via computed property for `isDirty` and Ember Inspector for `hasDirtyRelationships`).

**Comment by danielspaniel** [comment]
ok .. fair enough.  I actually did not test for manual tracking like you are doing, so let me test for that and make sure it is working

**Comment by danielspaniel** [comment]
ok .. try the latest 0.5.4 .. I can guarantee that this will fix the issue, if not reopen this

**Comment by mvrkljan** [comment]
Thanks @danielspaniel for prompt replies and updates!

I can confirm it now works for my use case, but only if I manually call `model.saveChanges()` after invoking save on the model.

However, if I add `auto: true` to model configuration then the computed properties behave correctly after invoking save, without any manual calls.

Not sure if this still behaves as you intended for a non-auto approach, but it does solve my issue so I won't be reopening this.

Thanks again!

**Comment by danielspaniel** [comment]
wait. 
 I tested this and if you are using v0.5.4 ( the very latest ) 
 you should NOT have to call model.saveChanges() 
 after save.
 In the code I check to see if you are using enableIsDirty:true 
 and if so the computed properties are reset 
 If you have to call this manually ( saveChanges ) then something is wrong .. 
 and I should fix it.

**Comment by mvrkljan** [comment]
Ok, I tested again without `auto: true` and calling just `startTrack()` and it works. Didn't have to call `saveChanges()`. Not sure what I did to not make it work the first time, but I now double checked and it looks good.

**Comment by danielspaniel** [comment]
great .. glad to hear .. thanks for confirming! 

    On Wednesday, March 29, 2017 9:57 PM, Martin Vrkljan <notifications@github.com> wrote:
 

 Ok, I tested again without auto: true and calling just startTrack() and it works. Didn't have to call saveChanges(). Not sure what I did to not make it work the first time, but I now double checked and it looks good.—
