### ISSUE TITLE
Associations dont get serialized when using keepOnlyChanged 

### ISSUE THREAD

**Issue by kevintraver** [danielspaniel/ember-data-change-tracker#16]
When using the `keepOnlyChanged` mixin, association changes don't get serialized.

**Comment by danielspaniel** [comment]
mmm .. errr .. really?  belongsTo or hasMany?

**Comment by kevintraver** [comment]
`belongsTo`. Im using `JSONAPISerializer`, if that helps

**Comment by danielspaniel** [comment]
did you => model.startTrack(); // Start tracking before all relationships were loaded
is your parent model using auto track ?
you show me very little of what is going on. can not help you without more details.
I can screenshare if you don't feel like pasting stuff and typing a ton of things

**Comment by kevintraver** [comment]
I added `changeTracker: { auto: true }`, to my model, and it's working now. Thanks!

**Comment by danielspaniel** [comment]
whooray .. easy fix!
