### ISSUE TITLE
belongsTo relationships set in createRecord aren't tracked properly

### ISSUE THREAD

**Issue by mwpastore** [danielspaniel/ember-data-change-tracker#19]
v0.5.6. `changeTracker.auto` is set to `true` in the global configuration. `order` belongsTo `project` (async); `project` hasMany `order` (async).

```javascript
let project = store.createRecord('project');
let order = store.createRecord('order', { project });

console.log(order.savedTrackerValue('project')); // => null
```

Calling `saveChanges()` and/or `startTrack()` on `order` has no effect on the outcome.

**Comment by danielspaniel** [comment]
can you write a test for this @mwpastore  ?? 
.. because I want to be sure that this fails in the current repo ( ember / ember-data version )

**Comment by mwpastore** [comment]
Hrrm, manual tracking and `set` doesn't seem to work either. I must be doing something terribly wrong...

**Comment by danielspaniel** [comment]
I reckon there is something fishy going on ( like fish swimming around your code ) because that is kind of a good point. 
 I gotta admit, it is kinda tricky to get all the options straight .. so I not making fun or anything.

**Comment by danielspaniel** [comment]
If you can't figure it out, let me know and I can screen hero with you to see if I can see the issue.

**Comment by mwpastore** [comment]
@danielspaniel I can't reproduce the issue in a test. Your `#createRecord()` test in `tests/unit/model-test.js` doesn't do anything I'm not doing... the `company` relationship is a perfect example of what I'm looking for. I wonder if FactoryGuy is "helping" somehow...

Anyway, here's a [Twiddle](https://ember-twiddle.com/3763c49088480ed3da122c90e3790cf5). Maybe I'm missing something obvious?

**Comment by danielspaniel** [comment]
check this twiddle out

https://ember-twiddle.com/bc7b009ab75f10986cb2b8838209f606?openFiles=routes.application.js%2C

first reason it did not work is because you were adding new record ( project ) to new record (order)
 that project had no id yet, so nothing to save. 

then the second issue was run loop . sometimes you have to wrap stuff in run loop because the way things fire ( callback like didLoad  / ready ) are kind squirrelly.

**Comment by mwpastore** [comment]
Ah, okay. Thank you. The problem is that I have a new project with a new order, and other new objects are hanging off of the project and the order as well. I need to take a "snapshot" of these objects and their relationships in this state so that they can change and optionally be reverted at a later time. I've written my own mixin for this purpose but was hoping to use changeTracker since I'm already using it elsewhere.

**Comment by danielspaniel** [comment]
Yeah .. that is bummer, but just not sure how you can achieve such magic as to somehow save the belongsTo  before it has an id?  I would be curious to see how you did that.

**Comment by mwpastore** [comment]
It's not very sophisticated, it just captures the property values I'm interested in on the `ready` hook.

```javascript
import Mixin from 'ember-metal/mixin';
import EmberObject from 'ember-object';

export default Mixin.create({
  ready() {
    this._super(...arguments);

    if (!this.get('isNew')) {
      return;
    }

    const propertyCache = this.set('propertyCache', EmberObject.create());
    this.get('cachedProperties').forEach(key => {
      propertyCache.set(key, this.get(key));
    });
  }
});
```

Another approach is to attach an observer to the property on `init` and capture the first non-null value.

**Comment by danielspaniel** [comment]
ok .. so you are getting that new belongsTo record ( before it has id ) and storing it in cachedProperties,  and then later it will have an id and your ready to go. 
 It's ugly .. but you gotta do what you gotta do sometimes ..

**Comment by mwpastore** [comment]
It's just an object reference at the end of the day. Right? Or am I missing something?

**Comment by danielspaniel** [comment]
yes, your right .. i realize that sounded a bit harsh, so pretend like I never said anything except 
 ... well ... you gotta do what you gotta do.
