### ISSUE TITLE
push/pushPayload bypasses changeTracker

### ISSUE THREAD

**Issue by mwpastore** [danielspaniel/ember-data-change-tracker#25]
Using push/pushPayload to apply a delta to an existing record bypasses the changeTracker.

**Comment by danielspaniel** [comment]
when you push a payload it restores the state to root.loaded.saved, but can you explain what your context is?
can't tell what the issue is yet till I see exactly what your doing.

**Comment by mwpastore** [comment]
Sorry, I should have provided more detail. The workflow is basically:

1. Create a new record and save it to the backend (or find an existing record)
1. Use pushPayload to change attributes of the saved record (think a websocket connection streaming updates)
1. The attributes do not show as changed on the record

**Comment by mwpastore** [comment]
Ah, I see what you're saying. That's working as attended. I need to use _push or find another way to do what I'm trying to do. Thanks @danielspaniel, sorry for the noise.

**Comment by danielspaniel** [comment]
right .. I do this all the time in my application, I update with push from websocket. 
Change tracker in fact does same thing.  Push like that to update only works when you are in root.loaded.saved  state, so there is nothing to track if you know what I mean .. goes from root.loaded.saved  to root.loaded.saved

**Comment by mwpastore** [comment]
Do you know of any way to take a delta in json:api format and apply it to an existing record, leaving it in a updated/unsaved state with changeTracker showing changed attributes?

**Comment by danielspaniel** [comment]
no, with a json payload you are always better of going through push/pushPayload because it will normalize the payload for you based on you serializer / attribute transforms. 

BUT, I have a technique that I use that broadcasts changed attributes that are being set by the websocket update before the change is applied so that models or others can listen to certain attributes changing. 

This may not be what you want. But if it is let me know.

**Comment by mwpastore** [comment]
What I'm trying is serialize a complex tree of models to localStorage so if the user leaves and comes back they won't lose any work. Sometimes the models are saved (and retrieved with findRecord), sometimes unsaved (and rehydrated with createRecord), sometimes saved with unsaved changes (findRecord+???). Clearly, this is a nightmare of my own making. 😬

**Comment by danielspaniel** [comment]
you are ambitious I will give you that much. I would say it is worth trying to do just for the fun.
