### ISSUE TITLE
computed property for hasDirtyRelationships?

### ISSUE THREAD

**Issue by inconduit** [danielspaniel/ember-data-change-tracker#3]
i'm in need of a computed property like `hasDirtyRelationships` that i can compose with `hasDirtyAttributes`.  the simple use case is binding the `disabled` property of a save button on a form in a template that is disabled until the underlying model has been modified.  

thanks for the work, this is a much needed addition to models.

**Comment by danielspaniel** [comment]
( Your super welcome )  and boy Adam, you are asking a good question there. 

  Are you saying that you would like to only enable "save" if they changed a relationship?
 I think so and that is where hasDirtyBlah ( Blah being the Relationship )  would come in.

 You could do this:
  When they change the relationship ( lets call it pet ) , on a person you have an action I presume:
```javascript 
  petChanged: false,  // set this property on component

  actions: {
      changePets(pet) {
        let person = get('mainModel');
        person.set('pet', pet);
        this.set('petChanged', person.didChange('pet'));
      }
  }
```

This way petChanged is your property  to watch for disabled, and you can set the property when they set the pet. If they go back to same pet, then it will be false, but when they change pet, it will be true. 
```html
  <button disabled={{not petChanged}}/>
```
 Does that help??

ps. the not helper is from ember-truth-helpers addon

**Comment by inconduit** [comment]
my use case is more complex than that - i'd like to disable save if no attributes nor relationships have changed on the model, like
```
<button disabled={{not model.hasDirtyAttributesOrRelationships}}>
```
with your addon, you have a `changed()` that tracks relationship changes, but what i need is a computed property that uses that function.  the big question is, what is the dependent key that will trigger recomputation when a relationship changes?

**Comment by danielspaniel** [comment]
Errr .. umm .. there is none right now. 
  You can ( for now ) ask if:
 ```javascrtipt
Ember.$.isEmptyObject(person.changed()) 
```
 same idea as above ( make your property yourself) 
 maybe I don't get it 100%, but sometimes you don't need computed property, since you know exactly when the model is changing, so you can compute the property yourself ( if you know what I mean? )

**Comment by inconduit** [comment]
definitely need a computed property if you want to avoid writing a manual check for every relationship.  imagine a model that has many relationships, bound to many select components on a form.  it's not very maintainable to have to write a manual check for each of them.

**Comment by danielspaniel** [comment]
I guess the thing is that I don't have access to the internals of ember data so I can't actually tell when a property changed ( without doing some crazy things ) ...
 
 which is why I am trying to help with workaround ( since it is nice the way they have the property hasDirtyAttributes right there on the model )  but ember-data can do because ember-data tracks more stuff like when you set something, which this addon does not

**Comment by janmisek** [comment]
My attempt for computed properties:

- hasDirtyRelations
- hasDirtyAttributes (overriding original ember-data computed because of nested tracking)
- isDirty

https://github.com/danielspaniel/ember-data-change-tracker/pull/5

**Comment by danielspaniel** [comment]
By the way @janmisek .. the version 0.5.0 of change tracker has your feature built in. 
 You can use it by just using the 
```
  changeTracker: {auto:true, enableIsDirty: true}
```
 in the environment or in the model 
 It will not work for object types ( as we discussed ) but should work for everything else

**Comment by inconduit** [comment]
wanted to follow up on this - all hail alex blom of isle of code https://github.com/isleofcode/ember-changed-relationships

**Comment by danielspaniel** [comment]
I already said that ember-change-tracker does have computed hasDirtyRelationships  a few comments ago. 
not sure how this other addon is related to that?  or the all hail part? me confused .. me puzzled
