### ISSUE TITLE
Issue with `rollback` not rolling back `hasMany`

### ISSUE THREAD

**Issue by caseklim** [danielspaniel/ember-data-change-tracker#4]
I'm trying to make use of the `rollback` function and it's not working in my case. I have auto-tracking set to `true`, and I have a `hasMany` relationship that contains a `belongsTo` relationship. I'm using Ember and ember-data @ 2.11.

When I call `rollback`, it uses the ids of the `hasMany` relationship (`configs`):

![screen shot 2017-02-14 at 12 03 39 pm](https://cloud.githubusercontent.com/assets/2915936/22946894/cb880f00-f2ad-11e6-9b5b-aabe604a0c31.png)
However, by the time it gets to the serializer's `normalize` function, `relationships` is empty, and the rollback is ineffective:

![screen shot 2017-02-14 at 12 04 14 pm](https://cloud.githubusercontent.com/assets/2915936/22946893/cb845040-f2ad-11e6-9457-0b921c64f3b3.png)

(Note: `type` is also `undefined`, which I was easily able to avoid by extending the `normalize` function by adding the type after the fact)

Am I misunderstanding how this addon should be used, or is there a genuine issue here? Thank you!

**Comment by danielspaniel** [comment]
Hmm .. ( nice graphics by the way ) and this is probably an edge case that I just never tested for.  It would be a big help if you could recreate this behaviour in a failing test in the change-tracker ( fork ) or your own, or if you want to give me the code for your models .. i can try and make the failure on my own.

**Comment by danielspaniel** [comment]
If you on ScreenHero I could take a look at this now too. Curious to see what those models and your use case looks like

**Comment by caseklim** [comment]
This is for work so I probably shouldn't share our code directly 😛  
Let me try and give you as many details as possible:

settings.js
```
export default DS.Model.extend({
  ...
  configs: DS.hasMany('config', { async: false }),
});
```

config.js
```
export default DS.Model.extend({
  ...
  schedule: DS.belongsTo('schedule', { async: false, inverse: null }),
  settings: DS.belongsTo('settings'),
});
```

schedule.js
```
export default DS.Model.extend({
  ...
  windows: DS.hasMany('window', { async: false, inverse: null }),
});
```

window.js
```
export default DS.Model.extend({
  ...
});
```

**Comment by danielspaniel** [comment]
So what are you trying to rollback .. a settings model?

**Comment by caseklim** [comment]
For the "settings" model, we overwrite `modelNameFromPayloadKey` to simply `return key;` since the model name should always be plural. We also have an initializer that defines "settings" as uncountable using `Ember.Inflector.inflector.uncountable`. Can try to provide more details there if necessary, not sure if that has something to do with the type being undefined.

The general use case here is that there's a page for the "settings" model that can be modified and then either saved or rolled-back.

**Comment by caseklim** [comment]
Thanks for the fast responses so far btw :simple_smile:

**Comment by danielspaniel** [comment]
in the serializer for 'settings' you mean ( you override modelNameFromPayloadKey )  .. can you send that just to be 100% certain I got it just as you have it

**Comment by caseklim** [comment]
Here's the serializer:

```
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
  modelNameFromPayloadKey(key) {
    return key;
  },
});
```

**Comment by danielspaniel** [comment]
got it .. i am trying to make a failing test now

**Comment by caseklim** [comment]
Thank you! Let me know if you need anything else

**Comment by danielspaniel** [comment]
what version of ember and ember-data ?

**Comment by caseklim** [comment]
Ember@2.11.0 and ember-data@2.11.1

**Comment by caseklim** [comment]
Ah and I've got another potential issue for you, `changed()` doesn't detect when a property on an element in a `hasMany` relationship changes. I'm not sure if it's intended to pick up those changes or not. Manually iterating over the `hasMany` relationship and calling `changed()` on each element returns the correct result, though.

**Comment by danielspaniel** [comment]
yes, that is correct.  I decided not to say a model changed in a hasMany if the model's attributes changed because it is still the same id.  But that is another story to make that happen ( which is possible ) .. 
 Maybe one day I will have an options to say .. hey follow the tree down to this level 
 but for now .. I don't follow down the tree more than one level

**Comment by danielspaniel** [comment]
But I am able to recreate your bug .. very interesting

**Comment by danielspaniel** [comment]
can you do me favour and do this

```javascript
  modelNameFromPayloadKey(key) {
    console.log('modelNameFromPayloadKey', key);
    return key;
  },
```
and tell me what you see

**Comment by caseklim** [comment]
When I try to rollback it's undefined, interesting

**Comment by danielspaniel** [comment]
I know .. really interesting .. this is a nice puzzler

**Comment by caseklim** [comment]
It seems to lose the reference to the model name in `_extractType` in JSONAPISerializer which is called from the `normalize` function:

```
_extractType: function _extractType(modelClass, resourceHash) {
      if (false) {
        var modelName = this.modelNameFromPayloadType(resourceHash.type);
        var deprecatedModelNameLookup = this.modelNameFromPayloadKey(resourceHash.type);

        if (modelName !== deprecatedModelNameLookup && this._hasCustomModelNameFromPayloadKey()) {
          (0, _emberDataPrivateDebug.deprecate)("You are using modelNameFromPayloadKey to normalize the type for a polymorphic relationship. This has been deprecated in favor of modelNameFromPayloadType", false, {
            id: 'ds.json-api-serializer.deprecated-model-name-for-polymorphic-type',
            until: '3.0.0'
          });

          modelName = deprecatedModelNameLookup;
        }

        return modelName;
      } else {
        return this.modelNameFromPayloadKey(resourceHash.type);
      }
```

Even though the model class is passed in, which could be used to get the type of the model, it tries to read the type off of `resourceHash`. In our case, `resourceHash` is only an object that looks as it does in the first screenshot I shared (defined as `props` there).

**Comment by caseklim** [comment]
Does attaching the model type to `props` in `rollback` before passing the object to `normalize` solve anything?

**Comment by danielspaniel** [comment]
yes, that helps alittle but ( now it knows the type ) .. but it still looses the relationships

**Comment by danielspaniel** [comment]
Looks like there are differences with JSONAPISerialializer and REST serializer ( which I tested on ) .. so I have to retest things with the JSONAPISerializer .. then, if I can get that working, you should be back in business.

**Comment by caseklim** [comment]
Ah interesting, I've been digging around myself but didn't make any progress. It'd be great if you could get this working with JSONAPISerializer, let me know if you need anything else from me

**Comment by danielspaniel** [comment]
Almost got it ..

**Comment by danielspaniel** [comment]
Ok @caseklim .. try this new release https://github.com/danielspaniel/ember-data-change-tracker/releases/tag/v0.4.0  and let me know if it does not work .. because I think it should.

**Comment by caseklim** [comment]
Hmm so this is what I see coming out of the `rollback` function, it has a reference to the relationship but the rollback is still ineffective:

![screen shot 2017-02-15 at 10 25 18 am](https://cloud.githubusercontent.com/assets/2915936/22989073/4bb0adc0-f369-11e6-8131-5c01335b21ce.png)

**Comment by danielspaniel** [comment]
bummer .. so close.
why is type on those config   "deployment-config"  .. is this polymorphic relationship?

**Comment by caseklim** [comment]
Ah no sorry, I had just simplified my models when I posted my model structure yesterday

I'm trying to figure out how exactly the rollback behavior is achieved. I put the initial JSON response I get through a `data = JSON.parse('...')` and fed that into `store.push(data)`. This didn't rollback elements that were added/removed to/from a hasMany relationship, but it did rollback the belongsTo relationship inside of the hasMany.

Could any of this have to do with the fact that a lot of my relationships are `async: false` or `inverse: null`? The initial JSON response I get has data `included`, but that data isn't pushed to the store in your `rollback` function

**Comment by danielspaniel** [comment]
async: false probably not .. but inverse: null maybe makes a difference.   could you chop out  the =>  inverse: null ( just to test out the theory )

**Comment by danielspaniel** [comment]
And to be clear, the rollback payload as 2 configs,  and when it is pushed to the store, it has no affect, and the settings model still only has 1 config?

**Comment by caseklim** [comment]
Hmm might be tricky to just chop out the inverse: null, since I'd have to set up the inverse relationship

Yes, if a config was removed from the relationship. Also, if a config was added to the relationship (3 configs) and when it's pushed to the store, it has no effect, and the settings model still has 3 configs

**Comment by danielspaniel** [comment]
well, maybe that is irrelevant, because a settings model hasMany configs and the config belongsTo settings, and the other relationships should not matter because in this case the configs on the settings are refusing to return to another state, and they are not inverse: null

**Comment by danielspaniel** [comment]
I might need to get more details ( as in why the config are development-config type ) ..
can you unsimplify it and give me the settings and config models again ( for now I will assume the schedule and window models are not important )

**Comment by caseklim** [comment]
product-settings.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  ...
  configs: DS.hasMany('deployment-config', { async: false }),
});
```

deployment-config.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  ...
  schedule: DS.belongsTo('deployment-schedule', { async: false, inverse: null }),
  settings: DS.belongsTo('product-settings'),
});
```

The ellipses represent basic attributes (i.e. "string" or "boolean"

**Comment by sylwiaeb** [comment]
I'm having pretty much the same issue. It works well when my relationship is not empty, ex. when there's 1 record I can add another one and rollback all when transitioning. Then when going back that other record is not there. But when my relationship is empty and I add the record then rolling back doesn't work. After going back that added record is still there.

**Comment by caseklim** [comment]
@sylwiaeb Is your issue across page transitions? The rollback is failing for me on a single page

**Comment by sylwiaeb** [comment]
Actually, I'm checking it on a single page. Before leaving the route, if I call `this.get('model').rollback();` and then `this.get('model').changed()` it returns true for my relationship that I'm tracking.

**Comment by caseklim** [comment]
Ah I see, you're right; that's also what I'm experiencing

**Comment by danielspaniel** [comment]
So, can I boil that down to hasMany is only broken ( not rolling back ) when starting with empty state and then adding things?

**Comment by sylwiaeb** [comment]
> So, can I boil that down to hasMany is only broken ( not rolling back ) when starting with empty state and then adding things?

@danielspaniel  In my case yeah. When it's not empty at the beginning then adding/removing and rolling back works. But when it's empty then after adding/removing and rolling `this.get('model').changed()` returns true for my relationship, same for `this.get('model').didChange('my-relationship')`.

All my relationships are async: true (I have coalesceFindRequests: true) and I call `startTrack()` when all are loaded.

**Comment by caseklim** [comment]
Not in my case, for me, the hasMany relationship already has elements in it and it doesn't rollback added or removed elements. Also, the belongsTo relationship in my hasMany isn't rolled back (this is irrelevant to the adding/removing issue, I believe).

**Comment by danielspaniel** [comment]
ok .. i am verifying that the return to empty does not work,  but your case @caseklim , I can't seem to verify yet.

**Comment by caseklim** [comment]
Ok, re: my comment that the belongsTo relationship in the hasMany isn't being rolled back might just be a symptom that the hasMany isn't being rolled back at all. I tried changing out the basic attributes on the elements in the hasMany and those weren't rolled back either

**Comment by danielspaniel** [comment]
Right .. I think I was saying before that the settings is supposed to rollback the config to the correct ones that were there before, but if you change the configs themselves they will not be rolled back. Seems like they should ( ideally ) .. but it takes extra trickey to do this and some people don't want that, so I left it out for now.  You have to rollback those configs manually if you know what I mean.

**Comment by caseklim** [comment]
Ah I see, that's good to know. I can roll them back manually then, and the real issue remains that the added/deleted elements in the hasMany relationship aren't rolled back

**Comment by danielspaniel** [comment]
how are you adding deleteing?  I can only recreate the issue where they won't go back to empty .. but not go back to the 1 or the 2 that were there .. that seems to work ok.

**Comment by caseklim** [comment]
Adding to the hasMany:
```
addConfig() {
      const productSettings = this.get('settingsModel');
      const productName = this.get('productName');
      const newDeploymentConfig = productSettings.store.createRecord('deployment-config', {
        productName,
      });

      productSettings.get('configs').addObject(newDeploymentConfig);
      this.notifyPropertyChange('hasDirtyAttributes');
},
```

Deleting from the hasMany (where configModel is passed in from an #each):
```
removeConfig(configModel) {
      configModel.deleteRecord();
      this.notifyPropertyChange('hasDirtyAttributes');
},
```

**Comment by danielspaniel** [comment]
got it, what does ```this.notifyPropertyChange('hasDirtyAttributes');``` do for you?

**Comment by caseklim** [comment]
That's where I call `.changed()`, since there isn't a property on `settingsModel` that I can observe:
```
hasDirtyAttributes: computed('settingsModel', function () {
    const productSettings = this.get('settingsModel');
    const deploymentConfigs = get(productSettings, 'configs');

    const isProductSettingsChanged = Object.keys(productSettings.changed()).length !== 0;
    const isDeploymentConfigsChanged = deploymentConfigs.toArray().any((configModel) => {
      return Object.keys(configModel.changed()).length !== 0;
    });

    return isProductSettingsChanged || isDeploymentConfigsChanged;
  }),
```

**Comment by danielspaniel** [comment]
your overriding the original but don't care about the normal attributes so you don't call _super to get the result of that and do you own things with changed relationships  .. got it

**Comment by caseklim** [comment]
Should I be calling `_super` somewhere? I could be inadvertently doing something wrong, what would you expect me to be doing in my examples?

**Comment by danielspaniel** [comment]
you know .. that is a good question .. this computed property is already set on the model by ember-data .. so you actually can't call super because you overwrote that computed prop.  Calling super will not work ( my mistake ) .. but I was just curious how you are getting any info from the original computed prop hasDirtyAttributes to see if the regular attributes changed

**Comment by caseklim** [comment]
Ah, I should note that the `hasDirtyAttributes` computed property is being defined on a component in this case, so it's actually not overriding anything. Before I tried out your addon, I was doing the following:
```
hasDirtyAttributes: computed('settingsModel', function () {
    const productSettings = this.get('settingsModel');
    const deploymentConfigs = get(productSettings, 'configs');

    const isProductSettingsChanged = productSettings.get('hasDirtyAttributes');
    const isDeploymentConfigsChanged = deploymentConfigs.toArray().any((configModel) => {
      return configModel.get('hasDirtyAttributes');
    });

    return isProductSettingsChanged || isDeploymentConfigsChanged;
  }),
```
This worked for the most part, but I believe it couldn't detect when the belongsTo relationship on a deployment-config was changed

**Comment by danielspaniel** [comment]
Ok .. whew .. that cleared up the confusion.  That is interesting idea .. to put the computed prop in the component.  I do something similar as well since I don't have a computed property in change tracker

**Comment by sylwiaeb** [comment]
@danielspaniel Any chance that rolling back an empty case is fixable?

**Comment by caseklim** [comment]
Ideally, the change tracker might provide a computed property instead of or in addition to the `.changed()` function but that's a separate thing :)

**Comment by danielspaniel** [comment]
@sylwiaeb .. I think it's a bug in ember-data and I submitted an issue just now.
https://github.com/emberjs/data/issues/4804
So, for now now, it's not fixable, might take a while ( not sure )

**Comment by danielspaniel** [comment]
Sure thing @caseklim, if I could figure out how to do that computed property I would. I am just not sure how to do it

**Comment by sylwiaeb** [comment]
> .. I think it's a bug in ember-data and I submitted an issue just now.
> emberjs/data#4804
> So, for now now, it's not fixable, might take a while ( not sure )

@danielspaniel Thanks! I really like this plugin and appreciate your work and will keep an eye on it. In the meantime, I will go with very simple custom solution and create a service to cache initial values and ids for the relationships I'm interested in tracking, and set them back on the model when rolling back. To check of the relationship has changed I will compare initial ids with current ids - not ideal but will work for now.

**Comment by danielspaniel** [comment]
I hear you @sylwiaeb, I was doing similar hacky things before I put this addon together. 

But on the good news side of things, @sylwiaeb  and @caseklim  .. can you check out the new version and see if it works for you?
https://github.com/danielspaniel/ember-data-change-tracker/releases/new?tag=v0.4.1

I fixed these issues but doing a slight modification for rolling back hasMany. 
 I have it pretty well tested, but might have missed something.

**Comment by caseklim** [comment]
I pulled down the new version and rolling back deleted records in the hasMany still wasn't working. I changed my code from this:
```
removeConfig(configModel) {
  configModel.deleteRecord();
},
```
to this:
```
removeConfig(configModel) {
    const productSettings = this.get('settingsModel');
    productSettings.get('configs').removeObject(configModel);
 },
```
and now it's working (yay!). The only downside to this is I might still have to keep track of the records that were removed from the hasMany and delete them prior to saving. How are you expecting items to be removed from a hasMany relationship? I wonder if you could check for `isDeleted` and un-delete a record prior to pushing it to the store in your `rollback` function, as I'm assuming the record is still marked as deleted (I filter out on the `isDeleted` property in my template)

Thank you for keeping at this issue and trying to solve it :)

**Comment by danielspaniel** [comment]
Ohh .. yeah .. your welcome @caseklim .. this one has been really tricky to solve. 
  Now your case is actually an intersting one, and I can't technically do anything is you .deleteRecord  a record, because ember-data does not remove a record if you delete it .. only if you destroyRecord it. If you follow my drift. 
 The computed property which you have that shows the non deleted is good to show on the template, but does not affect the actual hasMany ( which you know already ) 
 So I can't really filter out the isDeleted ( because that would be an abuse of power ?? or something like that ) 
 I reckon you really have to removeObject to tell the hasMany that it is removed.

**Comment by caseklim** [comment]
Ah, I did not realize the nuance between `deleteRecord` and `destroyRecord`. Since there is a path forward where hasMany relationships can be rolled back, I think we can close this issue. @sylwiaeb, assuming your issue is fixed now as well

@danielspaniel Thank you again for the continued support over the past couple of days :)
