### ISSUE TITLE
Pushing a belongsTo change causes record to be dirty.

### ISSUE THREAD

**Issue by DuckoDeath** [danielspaniel/ember-data-change-tracker#40]
If I have a record which is not dirty, and now push an update to the store that contains a belongsTo update (for that record), the record will be dirty after the push.

```javascript
test('when model.belongsTo is pushed to store, do not dirty', function(assert) {
  let company1  = make('company');
  let company2  = make('company');

  let userJson = build('user', {id: '1111',name: 'bob',company: company1});

  let normalized = Tracker.normalize(make('user'), userJson.get());

  let user = run(() => FactoryGuy.store.push(normalized));
  assert.deepEqual(user.get('name'), 'bob', 'newly pushed user has correct info');
  assert.deepEqual(user.savedTrackerValue('company'), {id: company1.id, type: 'company'}, 'newly pushed user has correct company');
  assert.notOk(user.get('isDirty'), 'newly pushed user is not dirty');

  userJson = build('user', {id: '1111', company: company2});
  normalized = Tracker.normalize(make('user'), userJson.get());
  delete normalized.data.attributes.name;
  let user3 = run(() => FactoryGuy.store.push(normalized));
  assert.equal(user, user3, 'pushed update is the same user');
  assert.deepEqual(user3.get('name'), 'bob', 'pushed updated user has correct info');
  assert.deepEqual(user.savedTrackerValue('company'), {id: company2.id, type: 'company'}, 'tracker has correct company');
  assert.deepEqual(user3.belongsTo('company').id(), "2", 'pushed updated user has correct company');
  assert.notOk(user3.get('isDirty'), 'pushed update user is not dirty');
});
```

**Comment by danielspaniel** [comment]
Howdy, I read you email, but can you ( for the sake of others peeking here ) explain what you hope to accomplish and what you mean by this test?

**Comment by DuckoDeath** [comment]
This is simulating an external update (via websockets or some other process).
Where I have a record (that isn't dirty), and it's getting pushed to the store (an update).
Therefore I would expect that record to stay 'not dirty'.
But you will see if you run this test, the last assert fails, and the record is dirty after the push.

**Comment by danielspaniel** [comment]
just for funs sake you can actually do this 

```js
let company1  = make('company');
let userJson = build('user', {id: '1111',name: 'bob', company: company1}});
```

**Comment by danielspaniel** [comment]
so your changing the company by pushing the new company to the store .. right? 
 and you want the record to be marked as dirty?

**Comment by DuckoDeath** [comment]
Yes, I am pushing a changed company to the store.
But no, I do NOT want the record marked as dirty, but it is currently getting marked that way.

**Comment by danielspaniel** [comment]
Are these models from the change-tracker repo?  So user and company are from there?

**Comment by DuckoDeath** [comment]
yes, you can paste that test right into model-test.js
I wasn't smart enough to create a git patch, or fork :)

**Comment by danielspaniel** [comment]
no worries, I just pasted that sucker in there

**Comment by DuckoDeath** [comment]
Note: I did edit that code above to make your suggested change and add one more tracker assert.
Thanks!

**Comment by danielspaniel** [comment]
ok ... me checking

**Comment by danielspaniel** [comment]
what version of ED are you using?

**Comment by danielspaniel** [comment]
looks like I am going to have to change the README from 

## Known Issues
  - Ember less than 2.10 AND you are using auto track mode
   - When pushing data to the store directly to create a model ( usually done when using 
     websockets .. but same issue if using factory guy) you need to call ```model.saveChanges()``` 
     manually after creating that new model   

to 

## Known Issues
   - When pushing data to the store directly to create a model ( usually done when using 
     websockets .. but same issue if using factory guy) you need to call ```model.saveChanges()``` 
     manually after creating that new model

**Comment by DuckoDeath** [comment]
pulled your project, so whatever is in your package.json (2.15.x)

**Comment by danielspaniel** [comment]
so, you have to push the changes from the websocket and then call model.saveChanges()
ED is not invoking the didUpdate hook when you push to the store  as you can see me beefing about it here:  https://github.com/emberjs/data/issues/3748

**Comment by danielspaniel** [comment]
the documentation should have said .. you ALWAYS have to call model.saveChanges() after pushing to store

**Comment by DuckoDeath** [comment]
I expected this answer, and have already implemented....BUT....
I have a case where that doesn't work either :)

Imagine now I have a record that is dirty, I changed the company for example.
While that is dirty, I get an update pushed which doesn't change the company, but changes something else (like a contact or something).
I need my record to stay dirty with my dirty change.

We handle this by pruning out user changed properties from the payload before we push to the store (so my user changed properties don't get affected and my record is still dirty with my change dvalue). But calling saveChanges after the push breaks that and marks the record clean.

As I work around, I would need a saveChanges(excludingKeys)
Where I can pass which keys to skip.
I could create another test with this example if it would help.

Thoughts?

**Comment by danielspaniel** [comment]
.. yeah .. i gotcha .. another test might be nice to show others what to do .. 
 but I think your stuck with the workaround ( unless you can think of a way to implement that workaround in change-tracker ) .. as your saying ,  you could have a method like  .saveSomeChanges(excludeKeys)   because saveChanges(model) already takes the model as args ( but sure, you could add options to that I suppose ) 

 This is kind of a good use case though because that is exactly what you want. The model to update new things, but then be able to still be dirty for other attrs that it is changing. 

 I could help you with that .. we could get on slack and chit chat about it if you want ( over weekend is good time )

**Comment by DuckoDeath** [comment]
I created a fork.
I will create some more tests and implement a saveSomeChanges() or overload saveChanges(), not sure yet.

Thanks.

**Comment by danielspaniel** [comment]
gotcha .. no problem ..

**Comment by danielspaniel** [comment]
can you give v0.7..4  ( just made it ) a try ?  let me know if it works for you

**Comment by DuckoDeath** [comment]
works for me.
BUT, it is saveTrackerChanges({except: ['blah']})
'except' not 'excludes'
Thanks for the quick turnaround!

**Comment by danielspaniel** [comment]
oh yeah .. i just forgot and put except since I use that in other options thing in this library .. and thanks for letting me know it works 👍
