### ISSUE TITLE
hasDirtyRelations becomes stale

### ISSUE THREAD

**Issue by DuckoDeath** [danielspaniel/ember-data-change-tracker#42]
model-ext.js has saveChanges() defined as:
```javascript
  saveChanges(options) {
    Tracker.setupTracking(this);
    Tracker.triggerIsDirtyReset(this);
    Tracker.saveChanges(this, options);
  },
```

but the triggerIsDirtyReset occurs before the saveChanges, so if you have a something watching/observing isDirty, it can/might/will compute the new value of isDirty before the tracker is cleared by saveChanges.

I would suggest the order should be:
```javascript
  saveChanges(options) {
    Tracker.setupTracking(this);
    Tracker.saveChanges(this, options);
    Tracker.triggerIsDirtyReset(this);
  },
```

This is definitely happening in our app, but I can't find an easy way to write a test in your project,
I think you would need an integration test with an hbs watching record.isDirty.

**Comment by DuckoDeath** [comment]
Here is modification to 'resets on update' that fails due to the observer on isDirty

```javascript
       test('resets on update', async function(assert) {
        let [company1, company2] = makeList('company', 2),
            [detail1, detail2]   = makeList('detail', 2),
            project              = make('project', {details: [detail1], company: company1});

        project.startTrack();

        EmberObject.extend({
            record: null,
            init() {
              this.isDirtyObserver();
              return this._super(...arguments);
            },
            isDirtyObserver: observer('record.isDirty', function() {
              this.get('record.isDirty');
            })
        }).create({record: project});

        run(() => project.setProperties({title: 'Blob in Space', company: company2}));
        project.get('details').addObject(detail2);

        mockUpdate(project);

        await run(async () => project.save());
        assert.equal(project.get('isDirty'), false);
        assert.equal(project.get('hasDirtyAttributes'), false);
        assert.equal(project.get('hasDirtyRelations'), false);
      });
```

just comment out that EmberObject creation and it passes again.
Interesting that it fails even though the created object is not assigned to anything and must immediately go out of scope.

I can fork and create a test if you prefer.

Thanks.

**Comment by danielspaniel** [comment]
this is  a bizzarre use case and your right .. the whole thing is interesting, and officially makes no sense to me that the test should even fail at all .. but you get one more pet rock because you actually made a test that fails ( even though I have no idea why ) 
 but your right the moving the order in saveChanges passes test 

 you could also use run.once in the observer  but I gonna just change order like you suggested

**Comment by danielspaniel** [comment]
new version v0.7.5  has the fix for this issue ( enjoy you new elvis themed pet rock arriving in the mail soon )

**Comment by DuckoDeath** [comment]
Maybe your comment was rhetorical, but in case it wasn't...

It fails because notifyPropertyChange fires the watchers immediately/synchronously. You would think ember would kick that off in a 'next' or something, but it doesn't. So the observer gets the thread and evaluates/gets the isDirty/hasDirtyRelations before the tracker gets cleared, then the computed property has a cached value and never get computed again.

As for the garbage collection/unused object creation, who knows...javascript magic.

As for the new pet rock, so excited, can't wait 👍
