### ISSUE TITLE
new record is dirty after save

### ISSUE THREAD

**Issue by DuckoDeath** [danielspaniel/ember-data-change-tracker#43]
It appears new records which are saved do not have their tracker data reset (via saveChanges).

Specifically in model-ext.js
```javascript
  // when model updates, update the tracked state if using auto save
  saveOnUpdate: Ember.on('didUpdate', function() {
    if (Tracker.isAutoSaveEnabled(this) || Tracker.isIsDirtyEnabled(this)) {
      this.saveChanges();
    }
  }),
```

There would need to be another of these.
```javascript
  // when model updates, update the tracked state if using auto save
  saveOnCreate: Ember.on('didCreate', function() {
    if (Tracker.isAutoSaveEnabled(this) || Tracker.isIsDirtyEnabled(this)) {
      this.saveChanges();
    }
  }),
```

otherwise after a new record is saved, it is still dirty due to relations being dirty.
Unless I'm missing something?

**Comment by danielspaniel** [comment]
I already have this ( and it is tested )
```js 
// save state when model is loaded or created if using auto save
  setupTrackerMetaData: Ember.on('ready', function() {
  ...
```

**Comment by DuckoDeath** [comment]
but 'ready' is when the record is created locally, not when the POST comes back.

**Comment by danielspaniel** [comment]
let me check on that .. will write a test and fix it if that is not working

**Comment by DuckoDeath** [comment]
Awesome, thanks!

FYI, I just stuck this at the end of your 'test model newly created'
```javascript
  user.set('company', company);
  mockCreate(user);
  
  await run(async () => user.save());
  assert.notOk(user.get('isNew'));
  assert.notOk(user.get('isDirty'));
```

**Comment by danielspaniel** [comment]
simple .. good idea

**Comment by danielspaniel** [comment]
what is this testing again?  

because before the save the model is NOT dirty 
then you save it and it is still not dirty .. 

 so you tested what ?    me not sure?

**Comment by DuckoDeath** [comment]
after the company set, the record IS dirty.
We are testing that it is NOT dirty after the save (the last assert will currently fail)
more like:

```javascript
  user.set('company', company);
  assert.ok(user.get('isNew'));
  assert.ok(user.get('isDirty'));
  mockCreate(user);
  
  await run(async () => user.save());
  assert.notOk(user.get('isNew'));
  assert.notOk(user.get('isDirty'));
```

**Comment by danielspaniel** [comment]
strangely .. that is not what i am seeing

**Comment by danielspaniel** [comment]
I take it all back .. and owe you a pet rock .. you were right

**Comment by danielspaniel** [comment]
new version v0.7.5  has the fix for this issue ( enjoy you new chris rock themed pet rock arriving in the mail soon )

**Comment by DuckoDeath** [comment]
excellent and thanks.
