### ISSUE TITLE
rollback of pristine model with hasMany causes removal of hasMany elements

### ISSUE THREAD

**Issue by ashrafhasson** [danielspaniel/ember-data-change-tracker#57]
Hi, thanks for the useful addon!

I've been using the rollback feature on a model that has a `hasMany` collection of another model but when rolling this parent model back, even when its in a pristine condition, i.e., the parent model has no changes and the child `hasMany` models all have no changes and the `hasMany` relationship itself was not modified (as in no models were added or deleted from the collection), it causes its `hasMany` collection to be emptied! The collection of `hasMany` models remain in the store though. The model was __not__ sideloaded with its `hasMany` though, so I wonder if this is a known limitation or whether it's a bug or just the way it's supposed to be?

Not sure if this is related to issue #4 

Thanks,

**Comment by danielspaniel** [comment]
yeah that issue #4 was had alot of nuances. 
 So, for your case, if you make a PR with a failing test, I will look at it and try to fix. Otherwise I can't help since I just waste my time guessing at finding the bug.

**Comment by ashrafhasson** [comment]
@danielspaniel by looking at the [current model unit test ](https://github.com/danielspaniel/ember-data-change-tracker/blob/master/tests/unit/model-test.js#L538), it seems you try to capture the scenario I describe but maybe your addon treats `hasMany` elements that are lazily loaded (not side-loaded), potentially via [normalizeFindHasManyResponse](https://emberjs.com/api/ember-data/3.7/classes/DS.JSONAPISerializer/methods/normalizeFindHasManyResponse?anchor=normalizeFindHasManyResponse), as newly added elements? (not sure) but I tried to mimick your test using [EDFG](https://github.com/danielspaniel/ember-data-factory-guy) deleting the `included` array but wasn't able to recreate my own issue were I use [DS.JSONAPISerializer](https://emberjs.com/api/ember-data/3.7/classes/DS.JSONAPISerializer) (i.e., the test does not fail :/). I'm happy to submit my test as is (which might not be helpful) or I can try to adjust it if there's a way to simulate JSONAPI?

**Comment by danielspaniel** [comment]
to mock the hasMany loading async 
 you can 

use the factory guy mock() helper the mock().return(json) 
  json being anything you want in there  

 or also use

 mockLinks(model, relationshipKey).returns({json})
 as long as you setup the parent to have a links url ( see the factory guy docs )

**Comment by ashrafhasson** [comment]
Yeah, I'm using `mockFindRecord('user').returns({json})` where `json["included"]` is deleted but that doesn't seem to help. I'll keep trying to reproduce or close the issue if I can't!

**Comment by ashrafhasson** [comment]
Okay, I've set `{ enableIsDirty: true, trackHasMany: true, auto: false }`, this seems to give the expected behaviour!
Before, I was tracking `hasMany` and had `auto` set to `true`. Closing the issue putting it down to config mis-understanding .. thanks for your help.
