### ISSUE TITLE
This addon will break when used together with ember-cli-mirage

### ISSUE THREAD

**Issue by synaptiko** [danielspaniel/ember-data-change-tracker#59]
It took us a while to figure out what the problem is but in our application we use both `ember-data-change-tracker` and `ember-cli-mirage`. After upgrade from `0.7.7` to `0.8.0` we noticed that if Mirage is enabled, methods like `startTrack()` are missing on all models.

I found a fix, it's about adding `before: 'ember-cli-mirage'` to https://github.com/danielspaniel/ember-data-change-tracker/blob/master/app/initializers/ember-data-change-tracker.js

But the problem is it will fail in case `ember-cli-mirage` is not present in the project. I was also trying to debug `ember-cli-mirage` but I wasn't able to find any place which I could fix to make this addon work.

Maybe authors of this addon would have some idea how to fix it. I'm not that familiar with the internals of Ember.js. The help would be very appreciated. Thank you

**Comment by danielspaniel** [comment]
I don't use mirage, so 1 solution would be to stop using mirage and use factory guy ( its better than mirage anyway ), another would be to stay with change tracker 0.7.7, another would be to keep trying to figure this out, because since I don't mirage I not going to spend hours and days fixing issue with mirage breaking change tracker ( if you know what i mean )

**Comment by synaptiko** [comment]
Thank you. I will check the factory guy and maybe I will spend some additional time debugging Mirage. I think I can close this issue as there doesn't seem to be anything to be done here. Thanks again

**Comment by Leooo** [comment]
@synaptiko out of curiosity, how did you fix this one? :)

**Comment by Leooo** [comment]
moving the initializer before ember-cli-mirage fixed it for me:

```
import {initializer as initialize} from 'ember-data-change-tracker';

export default {
  name: 'ember-data-change-tracker',
  after: 'ember-data',
  before: 'ember-cli-mirage',
  initialize
};
```

**Comment by synaptiko** [comment]
@Leooo yes, that's the fix described in my first comment and that's exactly what we ended up doing in our fork: https://github.com/bayzat/ember-data-change-tracker/commit/ec2d6c16ba0fa4fb5e8274ed075aa23807fce4ce
