### ISSUE TITLE
jQuery Deprecation

### ISSUE THREAD

**Issue by rickieshi** [danielspaniel/ember-data-change-tracker#61]
```Error: Using Ember.$() has been deprecated, use `import jQuery from 'jquery';` instead```
Traced it back to [this line](https://github.com/danielspaniel/ember-data-change-tracker/blob/master/addon/utilities.js#L34) in utilities.

Reference: deprecation [ember-views.curly-components.jquery-element](https://deprecations.emberjs.com/v3.x/#toc_jquery-apis)

**Comment by danielspaniel** [comment]
v0.9.0 removes jquery as dependency
