### ISSUE TITLE
Fix evented-api-usage deprecations with Ember Data 3.12

### ISSUE THREAD

**Issue by mayatron** [danielspaniel/ember-data-change-tracker#64]
After upgrading to Ember Data 3.12.0 I get many of these deprecation warnings:

`DEPRECATION: Called ready on <model>#<id> [deprecation id: ember-data:evented-api-usage]`

This appears to be a result of:

https://github.com/danielspaniel/ember-data-change-tracker/blob/c1253fd3efc98f370d3c967a56f60d1b4f7297bb/addon/model-ext.js#L97

Related: https://github.com/emberjs/rfcs/pull/329

**Comment by danielspaniel** [comment]
feel like helping fix those deprecations?   please make a PR and see if you can fix.

**Comment by danielspaniel** [comment]
fixed with your PR and is now on  => v0.9.1 

thanks again :)
