### ISSUE TITLE
Is this add-on still working?

### ISSUE THREAD

**Issue by csprocket777** [danielspaniel/ember-data-change-tracker#68]
I'm struggling to get any of the `isDirty` or `hasDirtyRelationships` to work. I've followed the installation instructions but I don't see any additional model capabilities.

**Comment by danielspaniel** [comment]
what version of ED are you using ?  this addon might be broken for latest versions like ED 3.13+

**Comment by csprocket777** [comment]
I'm using ember-data 3.7.0

**Comment by danielspaniel** [comment]
in that case works fine .. not sure how best to help you  -> try reading the tests  ?  

```I'm struggling to get any of the isDirty or hasDirtyRelationships to work. I've followed the installation instructions but I don't see any additional model capabilities.```

 just says you having trouble .. how can anyone help with so little info ?

**Comment by csprocket777** [comment]
I understand. Here are the steps that I went through.

**Comment by danielspaniel** [comment]
did you test the methods from change tracker ? 
 why don't you look at my tests , then make a test of your own. 
why you looking for computed properties on the model. i am so confused 
why you don't just call the change tracker methods and see if they working 
  write a unit test for models that does that and you will know why it not work or if it is working. 

  can't really help even with this info ( unless i have failing test to see the setup of model and what you really doing . 
you say "i looking for computed property" .. but did you call the methods on change tracker .. i have no idea without that test to prove it

**Comment by csprocket777** [comment]
I did look at your tests. They make use of the `make` function from the `ember-data-factory-guy` library. Which extends the model from ember-data, correct?

The documentation states the following:

- - -
This addon:
- tracks modifications in attributes that are object/json/custom type
- tracks replacement of belongsTo associations
- tracks replacement/changes in hasMany associations
- adds a modelChanges() method to DS.Model
- adds a rollback() method to DS.Model
- adds a isDirty computed property to DS.Model ( only if enabled in configuration )
- adds a hasDirtyRelations computed property to DS.Model ( only if enabled in configuration )
- - -

The above tells me I should be able to look for `isDirty` or `hasDirtyRelations` as computed properties on the model.

Since the above also references `DS.Model`, I assumed I didn't need to leverage the `ember-data-factory-guy` library in order to use `ember-data-change-tracker`.

> why you don't just call the change tracker methods and see if they working

I have called `modelChanges()` on the model after adding to the `hasMany` relationship and I get a result back that makes sense, however, I was hoping to respond to a computed property change elsewhere. Hence why I was looking for `hasDirtyRelations` to work.


> but did you call the methods on change tracker

Given the instructions, I have tried 2 approaches. 
1. Setting `auto` in the environment config to `true`, from what I understood meant that changes to the model would automatically be detected. Given this snippet in the instructions:
- - -
**auto:** should tracking be turned on by default? ( false is default )
- auto tracking means when any model is saved/updated/reloaded the tracker will save the current state, allowing you to rollback anytime

- - -

2. When the above didn't seem to work I tried setting it to false in the config and before making a change to the model did the following:
```
recordToChange.startTrack()
[changed hasMany relationship on recordToChange]
```
And still didn't see any computed properties telling me that a change happened to the relationship.

**Comment by danielspaniel** [comment]
you don't have to use factory guy . i just use it to create models for testing.

  how about if you make a PR of this repo, and then make a test to show how change tracker does not work? 

  or you can look over the tests i made and figure out that way.

  you could find our right away if it is change tracker or you with problem. 

   the tests in change tracker might be missing the check for  hasDirtyRelations ... I am just not sure .. but your welcome to add that test and fix it

**Comment by csprocket777** [comment]
Moving to another add-on.

**Comment by csprocket777** [comment]
So, to anyone else landing on this error in search for an answer, I figured out that my issue was in relation to the combination of usage with `ember-cli-mirage`. 

It's discussed in issue #59 

Except, in this case, if you create your own initializer with the same name, you can then override the addon initializer with your own and impose a load order without needing to fork this addon.

So:
1. `ember g initializer ember-data-change-tracker`
2. edit it to be the following:
```
import {initializer as initialize} from 'ember-data-change-tracker';

export default {
  name: 'ember-data-change-tracker',
  before: 'ember-cli-mirage',
  after: 'ember-data',
  initialize
};
```

Then you'll see features like `modelChanges()` appear on your ember-data models.
